name: Render

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Wait for Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Render Deployment
        uses: bounceapp/render-action@0.6.0
        with:
          render-token: ${{ secrets.RENDER_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          retries: 20
          wait: 16000
          sleep: 30000
      - name: Job Success
        uses: rjstone/discord-webhook-notify@v1.0.4 # Replace with the latest version
        if: ${{ success() }}
        with:
          severity: info
          details: 'Deployment Successful!'
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Job Failure
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: ${{ failure() }}
        with:
          severity: error
          details: Test Failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
